version: '3.8'
services:
    db:
        container_name: pg_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: fernandakipper
            POSTGRES_PASSWORD: password
            POSTGRES_DB: fernandakipper
        ports:
        - "5432:5432"
        networks:
        - postgres-compose-network      
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
        - "16543:80"
        depends_on:
        - db
        networks:
        - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge      